<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Stellar [
	<!ELEMENT home (about, contact-us, select-your-constellation)>
	<!ELEMENT select-your-constellation (Aries, Aquarius, Capricorn, Cancer, Gemini, Libra, Leo, Pisces, Scorpio, Sagittarius, Taurus, Virgo)>

	<!ELEMENT home (#PCDATA)>
	<!ELEMENT about (#PCDATA)>
	<!ELEMENT contact-us (#PCDATA)>
	<!ELEMENT select-your-constellation (#PCDATA)>
	<!ELEMENT Aries (#PCDATA)>
	<!ELEMENT Aquarius (#PCDATA)>
	<!ELEMENT Capricorn (#PCDATA)>
	<!ELEMENT Cancer (#PCDATA)>
	<!ELEMENT Gemini (#PCDATA)>
	<!ELEMENT Libra (#PCDATA)>
	<!ELEMENT Leo (#PCDATA)>
	<!ELEMENT Pisces (#PCDATA)>
	<!ELEMENT Scorpio (#PCDATA)>
	<!ELEMENT Sagitarrius (#PCDATA)>
	<!ELEMENT Taurus (#PCDATA)>
	<!ELEMENT Virgo (#PCDATA)>


]>
	


<home> 

	<about> </about>
	<contact-us></contact-us>
	<select-your-constellation>
		<Aries>Aries, (Latin: “Ram”) in astronomy, zodiacal constellation in the northern sky lying between Pisces and Taurus, at about 3 hours right ascension and 20° north declination. Aries contains no very bright stars; the brightest star, Hamal (Arabic for “sheep”), has a magnitude of 2.0. The first point of Aries, or vernal equinox, is an intersection of the celestial equator with the apparent annual pathway of the Sun and the point in the sky from which celestial longitude and right ascension are measured. The vernal equinox no longer lies in Aries but has been moved into Pisces by the precession of the equinoxes. In astrology, Aries is the first sign of the zodiac, considered as governing the period from about March 21 to about April 19. Its representation as a ram is identified with the Egyptian god Amon and, in Greek mythology, with the ram with the golden fleece, on the back of which Phrixus, the son of King Athamas, safely fled Thessaly to Colchis, where he sacrificed the ram to Zeus, who placed it in the heavens as the constellation. The ram’s golden fleece was recovered by Jason, leader of the Argonauts.</Aries>
		<Aquarius>Babylonian astronomers identified the constellation as representing the god Ea, or The Great One, which was often pictured with an overflowing vessel. In ancient Egypt, the water bearer's jar was said to cause the spring overflow of the Nile when it was dipped into the river.Aquarius, (Latin: “Water Bearer”) in astronomy, zodiacal constellation lying in the southern sky between Capricornus and Pisces, at about 22 hours right ascension and 10° south declination.
		Aquarius is depicted as a young man pouring water (or alternatively, nectar) from an amphora into the mouth of the Southern Fish, represented by the constellation Piscis Austrinus.
		Aquarius is usually associated with Ganymede, the son of King Tros, in Greek mythology. Ganymede was a beautiful Trojan youth who caught Zeus’ eye, which prompted the god to disguise himself as an eagle (represented by the constellation Aquila) and carry him off to Olympus to serve as cup-bearer to the gods. In a different story, the constellation represents Deucalion, son of Prometheus, who survived the great flood along with his wife Pyrrha.</Aquarius>
		<Capricorn>Capricornus, (Latin: “Goat-horned”) , also called Capricorn and the Goat, in astronomy, zodiacal constellation lying in the southern sky between Aquarius and Sagittarius, at about 21 hours right ascension and 20° south declination. Its stars are faint; Deneb Algedi (Arabic for “kid’s tail”) is the brightest star, with a magnitude of 2.9.In astrology, Capricornus (also called Capricorn) is the 10th sign of the zodiac, considered as governing the period from about December 22 to about January 19. One explanation of the fishtail with which the goat is often represented is found in the Greek myth of Pan, who, to avoid the monster Typhon, jumped into the water just as he was changing into animal shape. The half above water assumed the shape of a goat while the lower half, the tail, assumed the shape of a fish.</Capricorn>
		<Cancer>Cancer, which is Latin for crab, is the dimmest of the 13 constellations of the Zodiac, having only two stars above the fourth magnitude. Cancer lies between Leo, the lion, and Gemini, the twins. It is almost impossible to see Cancer as a crab with the naked eye or even binoculars. It looks more like a faint, upside-down Y.
		Cancer is visible in the Northern Hemisphere in the early spring. It can be seen in the Southern Hemisphere during autumn. The Cancer constellation occupies an area of 506 square degrees. The constellation of Cancer represents the giant crab that attacked Hercules during the second of the 12 labors he performed as penance for killing his family. It was sent by the jealous goddess Hera to thwart Hercules as he battled the water serpent Hydra, but he killed it with his club.</Cancer>
		<Gemini>Gemini, (Latin: “Twins”) in astronomy, zodiacal constellation lying in the northern sky between Cancer and Taurus, at about 7 hours right ascension and 22° north declination. Its brightest stars are Castor and Pollux (Alpha and Beta Geminorum); Pollux is the brighter of the two, with a magnitude of 1.15, and is the 17th brightest star in the sky. The summer solstice, the northernmost point reached by the Sun in its annual apparent journey among the stars, lies in Gemini. This constellation also contains the isolated pulsar Geminga. In astrology, Gemini is the third sign of the zodiac, considered as governing the period from about May 21 to about June 21. It is represented by a set of twins (or in Egyptian astrology by a pair of goats and in Arabian astrology by a pair of peacocks). In addition to their identification as Castor and Pollux, the twins have also been related to other celebrated pairs, such as the younger and older Horus or Romulus and Remus.</Gemini>
		<Libra>Libra, (Latin: “Balance”) in astronomy, zodiacal constellation in the southern sky lying between Scorpius and Virgo, at about 15 hours 30 minutes right ascension and 15° south declination. Its stars are faint; the brightest star, Zubeneschamali (Arabic for “northern claw,” as it was earlier regarded as part of Scorpius; also called Beta Librae), has a magnitude of 2.6. In astrology, Libra is the seventh sign of the zodiac, considered as governing the period from about September 22 to about October 23. It is represented by a woman (sometimes identified with Astraea, the Roman goddess of justice), holding a balance scale or by the balance alone.</Libra>
		<Leo>Leo, (Latin: “Lion”) in astronomy, zodiacal constellation lying in the northern sky between Cancer and Virgo, at about 10 hours 30 minutes right ascension and 15° north declination. Regulus (Latin for “little king”; also called Alpha Leonis), the brightest star, is of magnitude 1.35. The November meteor shower called the Leonids has its radiant, or point of apparent origin, in Leo. Many of the stars in Leo form an asterism called the Sickle. In astrology, Leo is the fifth sign of the zodiac, considered as governing the period from about July 23 to about August 22. Its representation as a lion is usually linked with the Nemean lion slain by Heracles (Hercules).</Leo>
		<Pisces>Pisces, (Latin: “Fishes”) in astronomy, zodiacal constellation in the northern sky between Aries and Aquarius, at about 1 hour right ascension and 15° north declination. The vernal equinox, the point where the Sun’s annual apparent path takes it north of the celestial equator and from which celestial longitude and right ascension are measured, lies in Pisces. The constellation contains only faint stars without any striking grouping; the brightest star, Eta Piscium, has a magnitude of 3.6.In astrology, Pisces is the 12th sign of the zodiac, considered as governing the period from about February 19 to about March 20. Its representation as two fish tied together is usually related to the Greek myth of Aphrodite and Eros, who jumped into a river to escape the monster Typhon and changed into fish, or, alternatively, the two fish that carried them to safety.</Pisces>
		<Scorpio>Scorpius, (Latin: “Scorpion”) also called Scorpio, in astronomy, zodiacal constellation lying in the southern sky between Libra and Sagittarius, at about 16 hours 30 minutes right ascension and 30° south declination. Its brightest star, Antares (Alpha Scorpii), the 15th brightest star in the sky, has a magnitude of 1.1. Its name comes from the Greek for “rival of Ares” (i.e., rival of the planet Mars) and was probably given because of the star’s red colour and brightness. The brightest X-ray source in the sky, Scorpius X-1, is found in this constellation.In astrology, Scorpius (or Scorpio) is the eighth sign of the zodiac, considered as governing the period from about October 24 to about November 21. Its representation as a scorpion is related to the Greek legend of the scorpion that stung Orion to death (said to be why Orion sets as Scorpius rises in the sky). Another Greek myth relates that a scorpion caused the horses of the Sun to bolt when they were being driven for a day by the inexperienced youth Phaeton.</Scorpio>
		<Sagittarius>Sagittarius, (Latin: “Archer”) in astronomy, zodiacal constellation in the southern sky lying between Capricornus and Scorpius, at about 19 hours right ascension and 25° south declination. The centre of the Milky Way Galaxy lies in the radio source Sagittarius A*. Near the western border of Sagittarius is the winter solstice, the southernmost point reached by the Sun in its apparent annual journey among the stars. This constellation also contains the Lagoon and Trifid nebulas. The brightest star is Kaus Australis (from the Arabic for “bow” and the Latin for “southern,” respectively; it is also called Epsilon Sagittarii), with a magnitude of 1.9. Many of the stars are arranged in the prominent asterism called the Teapot.</Sagittarius>
		<Taurus>Taurus, (Latin: “Bull”) in astronomy, zodiacal constellation lying in the northern sky between Aries and Gemini, at about 4 hours 20 minutes right ascension and 16° north declination. The constellation’s brightest star, Aldebaran (Arabic for “the follower”; also called Alpha Tauri), is the 14th brightest star in the sky, with a magnitude of 0.85. The constellation also contains the Crab Nebula (M1) and the Pleiades and Hyades star clusters.In astrology, Taurus is the second sign of the zodiac, considered as governing that portion of the year from about April 20 to about May 20. Its representation as a bull is related to the Greek myth of Zeus, who assumed the form of a bull to abduct Europa.</Taurus>
		<Virgo>Virgo, (Latin: “Virgin”) in astronomy, zodiacal constellation lying in the southern sky between Leo and Libra, at about 13 hours right ascension and 2° south declination. The constellation’s brightest star, Spica (Latin for “head of grain,” also called Alpha Virginis), is the 15th brightest star in the sky, with a magnitude of 1.04. Virgo contains the nearest large cluster of galaxies, the Virgo cluster, in which is located the giant elliptical galaxy Virgo A and PSR 1257+12, the pulsar around which the first extrasolar planets were discovered in 1992.In astrology, Virgo is the sixth sign of the zodiac, considered as governing the period from about August 23 to about September 22. It is represented as a young maiden carrying a sheaf of wheat. She is variously identified as a fertility goddess (the Babylonian and Assyrian Ishtar, among others) or the harvest maiden (the Greek Persephone and others).</Virgo>
	</select-your-constellation>

</home>